baseurl = "https://deadfate.rbind.io/"
languageCode = "en-us"
title = "算是紀錄一下"
theme = "hugo-xmin"
googleAnalytics = "UA-156464110-1"
disqusShortname = "deadfate"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/Tags/"
    weight = 4
[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [本站採用CC4.0授權](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh_TW) | [Github](https://github.com/deadfate-sky)"      
    highlightjsVersion = "9.18.1"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "python","yaml"]
    highlightjsTheme = "github"
	  likerID = "evan19983314"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true